### ISSUE TITLE
Performance for nested lock

### ISSUE THREAD

**Issue by JasperWoo** [PatrickTulskie/redis-lock#13]
Hi there, due to compound-key data model, we need to do nested lock like this:
`lock_by(id1)
      lock_by(id2)
          lock_by(sorted([id1,id2]))
          ...
          end
      end
 end
`
Is there a great overhead by doing such nested locks?

**Comment by PatrickTulskie** [comment]
I'm actually not really sure what will happen if you do that. Have you tried it out yet?

**Comment by JasperWoo** [comment]
Sorry. I'm not sure how I should test them. And I don't think it really matters now.
