### ISSUE TITLE
ensure in lock_for_update?

### ISSUE THREAD

**Issue by fehrsam** [PatrickTulskie/redis-lock#2]
What do you think about adding an `ensure` for the unlock in `lock_for_update`?  As is it will not unlock if an exception is thrown.  Just curious, thanks!

**Comment by PatrickTulskie** [comment]
Sure. Do you want to send a pull request?

On Jan 14, 2013, at 9:43 PM, Mellop notifications@github.com wrote:

What do you think about adding an ensure for the unlock in lock_for_update?
As is it will not unlock if an exception is thrown. Just curious, thanks!

—
Reply to this email directly or view it on
GitHubhttps://github.com/PatrickTulskie/redis-lock/issues/2.

**Comment by barmstrong** [comment]
Added! https://github.com/PatrickTulskie/redis-lock/pull/3

**Comment by PatrickTulskie** [comment]
Merged it all together and pushed out a new release this morning.  Sorry for taking so long!
